[tool.poetry]
name = "artificial-non-intelligence-api"
version = "0.1.0"
description = ""
authors = ["Adrien Carpentier <moi@adriencarpentier.com>", "Philip Lin <philip.lin@gmail.com>", "Dilnoza Mirdjalilova <dmirdjalilova@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
aiomysql = "^0.0.21"
fastapi = "^0.65.1"
uvicorn = "^0.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
