[tool.poetry]
name = "artificial-non-intelligence-api"
version = "0.1.0"
description = ""
authors = [
    "Adrien Carpentier <moi@adriencarpentier.com>",
    "Philip Lin <philip.lin@gmail.com>",
    "Dilnoza Mirdjalilova <dmirdjalilova@gmail.com>",
]

[tool.poetry.dependencies]
python = "^3.7"
aiomysql = "^0.0.21"
fastapi = "^0.65.1"
uvicorn = "^0.14.0"

[tool.poetry.dev-dependencies]


[tool.pdm]
includes = []
[tool.pdm.dev-dependencies]
dev = []
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "artificial-non-intelligence-api"
version = "0.1.0"
description = ""
authors = [
    { name = "Adrien Carpentier", email = "moi@adriencarpentier.com" },
    { name = "Philip Lin", email = "philip.lin@gmail.com" },
    { name = "Dilnoza Mirdjalilova", email = "dmirdjalilova@gmail.com" },
]
dependencies = [
    "aiomysql<1.0.0,>=0.0.21",
    "fastapi<1.0.0,>=0.65.1",
    "uvicorn<1.0.0,>=0.14.0",
]
requires-python = ">=3.7,<4.0"
dynamic = ["classifiers", "classifiers"]
license = { text = "MIT" }

[project.urls]
homepage = ""
