[tool.poetry]
name = "artificial-non-intelligence"
version = "0.1.0"
description = ""
authors = ["Adrien Carpentier <moi@adriencarpentier.com>", "Philip Lin <philip.lin@gmail.com>", "Dilnoza Mirdjalilova <dmirdjalilova@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.9.3"
chromedriver-binary = "^91.0.4472"
fastapi = "^0.65.1"
pandas = "^1.2.4"
peewee = "^3.14.4"
psycopg2 = "^2.8.6"
requests = "^2.25.1"
selenium = "^3.141.0"
typer = "^0.3.2"
uvicorn = "^0.14.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
